orders.get_allowed_time:
  path: /orders/getAllowedDateTime
  methods: GET
  defaults: { _controller: app.orders.controller:getAllowedDateTimeAction }

orders.list:
  path: /orders/
  methods: GET
  defaults: { _controller: app.orders.controller:indexAction }

orders.new:
  path: /orders/new
  methods: GET
  defaults: { _controller: app.orders.controller:newAction }

orders.create:
  path: /orders/create
  methods: POST
  defaults: { _controller: app.orders.controller:createAction }

orders.edit:
  path: /orders/edit/{id}
  methods: GET
  defaults: { _controller: app.orders.controller:editAction }

orders.show:
  path: /orders/{id}
  methods: GET
  defaults: { _controller: app.orders.controller:showAction }

orders.update:
  path: /orders/{id}
  methods: POST
  defaults: { _controller: app.orders.controller:updateAction }

orders.delete:
  path: /orders/{id}
  methods: DELETE
  defaults: { _controller: app.orders.controller:deleteAction }